### PR TITLE
Add PHP 8.2 to the upcoming versions list

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by localheinz** [comment]
@WyriHaximus 

Is there anything holding up this pull request?

See https://github.com/sebastianbergmann/phpunit/pull/4973#issuecomment-1134553216.

**Review by localheinz — APPROVED** [review]
👍

**Comment by WyriHaximus** [comment]
> Is there anything holding up this pull request?

@localheinz Was planning on waiting till I had 8.2 in https://hub.docker.com/r/wyrihaximusnet/php but if you and @sebastianbergmann can use it right now I can merge and tag a new release with this.

> See [sebastianbergmann/phpunit#4973 (comment)](https://github.com/sebastianbergmann/phpunit/pull/4973#issuecomment-1134553216).

That's amazing ❤️ !

**Comment by localheinz** [comment]
Thank you, @WyriHaximus!

**Pull request merged**
